### ISSUE TITLE
Change `strains` in `StrainCollection` to be a `set` instead of `list`

### ISSUE THREAD

**Issue by hechth** [sdrogers/nplinker#113]
the `self._strains` has the type `list[Strain]`. so the order of Strain objects in the list also matters for the comparison. Do we care about the order? Does it make more sense to change the type to `set[Strain]`?

_Originally posted by @CunliangGeng in https://github.com/NPLinker/nplinker/pull/111#discussion_r1114529354_

Only changing `self._strains` from list to set will not help if the `self.strain_dict_index` (the index is ordered) are still there.

**Comment by CunliangGeng** [comment]
It makes sense to use list to keep the order. We use list for the other object, e.g. `npl.gcfs, npl.spectra, npl.mfs`. It's expected that `npl.strains (which is a StrainCollection)` behaves like a list, so that in the scoring stage, the index and column names of data frame could be consistent for the same inputs (`npl.gcfs, npl.spectra, npl.mfs, npl.strains`).
