### ISSUE TITLE
Error when loading Crüsemann data

### ISSUE THREAD

**Issue by louwenjjr** [sdrogers/nplinker#38]
I am getting started with using NPLinker (using the docker image) so after completing the 'tutorial' using the example dataset, I tried to load the Crüsemann dataset (MSV000078836) from PoDP. However something goes wrong when retrieving the genome information, causing BiG-SCAPE to fail. This is the error it ultimately crashes with:
Exception: Failed to find *any* BiGSCAPE Network_Annotations tsv files under "/data/nplinker_data/pairedomics/extracted/MSV000078836/bigscape" (incorrect cutoff value? currently set to 30)

I attached the log file.

Thanks for the help!
[crus_log.txt](https://github.com/sdrogers/nplinker/files/5886420/crus_log.txt)

**Comment by andrewramsay** [comment]
Yes, looks like NPLinker was unable to retrieve any genomics data at all for this particular project. If everything works as intended, it is supposed to extract genome IDs from the project metadata stored on the platform, download the corresponding .gbk files from the antiSMASH database, and then finally run BiG-SCAPE on them. 

The problem here is that metadata for projects on the platform are not all in the same format. This project has the genome IDs stored in a form that NPLinker doesn't currently recognise. The lookup process is also unfortunately quite fragile because it relies on scraping a couple of different websites to find the required IDs/URLs. 

From a quick look I think I can see a way to resolve these particular IDs to the required form, but from past experience it probably won't work in every case so the result will likely be a partial collection of genomics files for the dataset. This will at least be enough to run BiG-SCAPE and have the webapp finish loading successfully though.

I'll see if I can get an updated version working later today or tomorrow and let you know once there's a new Docker image you can try out.

**Comment by louwenjjr** [comment]
Great. Thanks a lot!

**Comment by justinjjvanderhooft** [comment]
Thanks Andrew! It would be nice to get it to work for this (example) dataset for users to try it out as it is also used in the preprint. Let me know if we should add alternative IDs to the project if that makes the process easier (and if so, which ones....) - Joris and I could look into that.

**Comment by justinjjvanderhooft** [comment]
And it would be good to know what currently works with the PoDP downloader in NPLinker Andrew....

**Comment by andrewramsay** [comment]
That could be quite helpful! What happens in the current version is:

- Retrieve the "genomes" list from the project's JSON data
- Check if a 'RefSeq_accession' field exists in the 'genome_ID' dict for each entry in the list 
   - If found, that's used to go straight to the antiSMASH database
- If the 'RefSeq_accession' field doesn't exist, it falls back to checking for a 'GenBank_accession' field instead
   - If that field is found, it does an indirect lookup using ncbi.nlm.nih.gov to get a RefSeq_accession ID and then goes to antiSMASH
- If neither of those fields exist then it gives up

For a project like [MSV000079284](https://pairedomicsdata.bioinformatics.nl/projects/4b29ddc3-26d0-40d7-80c5-44fb6631dbf9.4), the per-genome data looks like this:

```{"genome_ID": {"genome_type": "genome", "JGI_Genome_ID": "2515154093", "RefSeq_accession": "GCF_000515175.1"}, "genome_label": "Salinispora arenicola CNB527"},```

which makes things very simple. But the Crüsemann data looks like this:

```{"genome_ID": {"genome_type": "genome", "JGI_Genome_ID": "2517572137"}, "genome_label": "Salinispora arenicola CNT005", "publications": "24616526"},```

So the problem with the current NPLinker is that it doesn't know what to do when JGI_Genome_ID is the only info available. If it's easy to update the metadata on the platform to include the RefSeq_accession IDs alongside the JGI ones that would be ideal, at least for this dataset. 

What I've started doing to work around the problem is adding another step to the lookup process, so it is capable of going from the JGI Genome database to NCBI to antiSMASH.

**Comment by justinjjvanderhooft** [comment]
Thanks Andrew - that's very useful to know. I think having that option in would be very useful so I am hoping that you can include this indeed. Also as I am not entirely sure if those RefSeq IDs exist.... @louwenjjr could you do some investigation and let us know what you find and we can take it from there.

**Comment by louwenjjr** [comment]
That is indeed very useful information.
@justinjjvanderhooft the refseq IDs do exist for the Crüsemann data, for example the one that Andrew mentioned: GCF_000514895.1 (https://www.ncbi.nlm.nih.gov/assembly/GCF_000514895.1/).

**Comment by justinjjvanderhooft** [comment]
Thanks @louwenjjr - given the number of strains we would need to check this for https://pairedomicsdata.bioinformatics.nl/projects/297c364c-b154-4edd-a7d5-68decf9effa2.4 I think it makes sense to see if it works through JGI @andrewramsay, but we could see if we can collect the RefSeq IDs and add them in as well....

**Comment by andrewramsay** [comment]
This is how I'm trying to do things at the moment:

1. Take the JGI_Genome_ID and use it to generate a search result page on the JGI site. That results in something like [this page](https://img.jgi.doe.gov/cgi-bin/m/main.cgi?section=TaxonDetail&page=taxonDetail&taxon_oid=2517572137) for ID 2517572137.
2. Extract the "NCBI GenBank ID" value from the table on that page
3. Pass that ID into the existing code for looking up GenBank IDs

This does work, but not for all cases. Of the 120 genomes listed in the Crüsemann data, it manages to sucessfully download 75 of them from antiSMASH. 

The failed ones seem to fall into 2 categories:
 
 - looking up the NCBI GenBank ID on the JGI site fails because the "GenBank ID" doesn't appear in the results, e.g. for [2561511036](https://img.jgi.doe.gov/cgi-bin/m/main.cgi?section=TaxonDetail&page=taxonDetail&taxon_oid=2561511036)
 - the JGI ID gets resolved to a GCF_[something] ID successfully, but searching for it on antiSMASH doesn't produce any matches. e.g. JGI ID [2515154186](https://img.jgi.doe.gov/cgi-bin/m/main.cgi?section=TaxonDetail&page=taxonDetail&taxon_oid=2515154186) gets resolved to GCF_000515015, but antiSMASH returns a [404 page](https://antismash-dbv2.secondarymetabolites.org/output/GCF_000515015) for it (when it's doing these lookups, the app queries both antismash-db.secondarymetabolites.org and antismash-dbv2.secondarymetabolites.org, and tries each domain with and without a ".1" suffix on the GCF_... ID)

Do either of you see anything I'm doing wrong or that could be improved here? NPLinker should run OK as long as it has at least some genomics data available but it would obviously be good to get as much as possible.

**Comment by justinjjvanderhooft** [comment]
That sounds like a reasonable approach to me @andrewramsay! JGI and NCBI are not fully synced, so it could well be that not everything is found at NCBI. Not entirely sure yet why those with GCF identity do not get a result from antiSMASHdb - if you have lists of these two types of errors you got, @louwenjjr and myself could look into this a bit further, and alternatively @louwenjjr could add genomic information manually, but for the purpose of getting a sense of what NPLinker does, 75 genomes is certainly better than 0 genomes! 😎

**Comment by louwenjjr** [comment]
That sounds like a good approach! With this fix I can at least look at some Crüsemann stuff in NPLinker already.

I will look into it why those RefSeqs don't return any antiSMASH information.. It would be nice to figure it out for this dataset as it's the main dataset used in the paper.

Maybe for future PoDP entries, it should be mentioned somewhere that RefSeq accessions should be added? @justinjjvanderhooft

**Comment by justinjjvanderhooft** [comment]
Well, if available of course @louwenjjr - alternatively you could download the genomes from JGI and run antiSMASH and BiG-SCAPE yourself and load it into NPLinker....

**Comment by justinjjvanderhooft** [comment]
@andrewramsay for the example you provided without NCBI ID, I followed the NCBI BioProject ID to the genome information: https://www.ncbi.nlm.nih.gov/genome/11829 where I could download a FASTA file....

**Comment by grimur** [comment]
That’s basically what I did, run antiSMASH and BiG-SCAPE manually - for the Crusemann data set, especially, I had a bunch of the genomic data lying about already.
-

On 28 Jan 2021, at 18:33, Justin van der Hooft <notifications@github.com> wrote:

﻿

Well, if available of course @louwenjjr<https://github.com/louwenjjr> - alternatively you could download the genomes from JGI and run antiSMASH and BiG-SCAPE yourself and load it into NPLinker....

**Comment by justinjjvanderhooft** [comment]
@grimur I see. Yes, probably from earlier downloaded versions. Could you perhaps share the contents of the folders Joris would need to load all the data files correctly at some point? For now, the fix of @andrewramsay will allow him to get used to things, but it would be nice for him to copy the results of the NPLinker preprint at some point....

**Comment by andrewramsay** [comment]
> That sounds like a reasonable approach to me @andrewramsay! JGI and NCBI are not fully synced, so it could well be that not everything is found at NCBI. Not entirely sure yet why those with GCF identity do not get a result from antiSMASHdb - if you have lists of these two types of errors you got, @louwenjjr and myself could look into this a bit further, and alternatively @louwenjjr could add genomic information manually, but for the purpose of getting a sense of what NPLinker does, 75 genomes is certainly better than 0 genomes! 😎

OK - I'll need to tidy up the code a bit but should definitely have a new Docker image ready at some point tomorrow. 

The full breakdown of the 120 genome lookups seems to be 75 successful, 30 failed matches on NCBI, and 15 failed on antiSMASH. 

These are the 30 JGI IDs that don't produce NCBI matches (at least the way I'm doing it):

```2561511036
2563366734
2561511115
2561511039
2571042006
2563366539
2563366517
2561511034
2571042009
2565956527
2571042016
2561511114
2563366531
2563366533
2561511103
2561511038
2571042007
2561511110
2561511108
2561511105
2561511113
2563366532
2571042345
2561511109
2563366534
2565956528
2571042008
2561511107
2561511111
2517572162
```
and these are the pairs of original & resolved IDs which it can't find on antiSMASH:
```2526164712,GCF_000425925
2561511104,GCF_000702345
2515154125,GCF_000519145
2521172655,GCF_000378705
2515154186,GCF_000515015
2518285563,GCF_000374705
2814122978,GCF_006716065
2524023246,GCF_000424725
2518645624,GCF_000377065
2515154135,GCF_000514615
2548876972,GCF_000259635
2548876909,GCF_000259675
2515154193,GCF_000514915
2515154088,GCF_000515135
2518645627,GCF_000377045
```

**Comment by louwenjjr** [comment]
Thanks for the list Andrew, I will look into it a bit today.

**Comment by louwenjjr** [comment]
I think your pipeline is working nicely, as I couldn't find a way to solve these issues, the RefSeq IDs simply do not exist, or the genomes are just not included in antismash-db.

My guess for the IDs that it can't find on antiSMASH is that these are genomes that are very similar to other Salinispora genomes so they did not reach the fastANI cutoff to be selected in antismash-dbv2.

**Comment by andrewramsay** [comment]
There's an updated Docker image ready for you to try out now, run ```docker pull andrewramsay/nplinker:latest``` to get it. 

Since I changed a lot of the code dealing with the genome downloading, I'd recommend deleting any existing files for the dataset so it can start fresh. Removing these 2 folders should take care of that:
```
nplinker_shared/nplinker_data/pairedomics/extracted/MSV000078836
nplinker_shared/nplinker_data/pairedomics/downloads/MSV000078836
```

It'll take a while to download everything because there are at least a couple of HTTP requests required for each genome entry, but you can interrupt the process at any point and it should resume where it left off next time (I might look into making multiple requests in parallel to speed this up at some point). 

I've tried going through the whole loading process a couple of times now and it seems to work OK.

**Comment by louwenjjr** [comment]
Really nice! Thanks a lot.
