### ISSUE TITLE
large-scale sample run error

### ISSUE THREAD

**Issue by jeep3** [sdrogers/nplinker#43]
Hi, Andrew, 
              I recently ran a large dataset using NPLinker and it loaded successfully, but I can't open the web application. Can you give some advice on how to solve it? Here is the log I copied. Thanks a lot. 

Best,
Huali

**Comment by andrewramsay** [comment]
I think this is just a bug caused by it not properly checking for the case where there are no rosetta hits to load from the usual file. I will try to upload a fixed version tomorrow, but for now you could probably work around it manually by creating a "rosetta" folder in your dataset folder, then creating an empty file called "rosetta_hits.csv" inside that.

**Comment by jeep3** [comment]
It still have bug after creating a new rosetta folder and then creating an empty file called "rosetta_hits.csv" in it. The newly created "rosetta_hits.csv" is automatically overwritten by another one called "bgc_hits.pckl" after running nplinker software. Here's the log, 
[20210627-log.txt](https://github.com/sdrogers/nplinker/files/6722317/20210627-log.txt)

**Comment by jeep3** [comment]
Many thanks for help me to debug, Andrew.

**Comment by andrewramsay** [comment]
Looks like the empty file you created would have been automatically deleted by another part of the code and that's why it didn't help. 

I've just pushed a new Docker image with a small update that I think should fix the problem, try pulling that and loading your dataset again.

**Comment by jeep3** [comment]
Thanks, Andrew, No problem now.
