### ISSUE TITLE
Error loading tutorial data

### ISSUE THREAD

**Issue by jcpasion** [sdrogers/nplinker#44]
Hello,

I am trying to use NPLinker that is hosted through Docker. Eventually I would like to use my own dataset, but right now I have been following the tutorial page titled WebappInstallation. Working from the command line,  pulling the Docker image worked fine. However, after I set up the config file and use the command to start the Webapp, I get this error message:

[NPLinker_Error.txt](https://github.com/sdrogers/nplinker/files/6773238/NPLinker_Error.txt)

Any idea what is going on? The error message I get is not found inside downloader.py so I do not know where it is coming from.

Thanks in advance for any guidance you can give!

**Comment by andrewramsay** [comment]
That's an odd one. Looks like it has just completely failed to connect to the Paired Omics Platform website to download the initial set of project metadata. No idea why that is happening, it seems to be working fine when I try it!

I guess there are a couple of quick checks you could make:

First, can you access the same URL outside of Docker, just by visiting it in a browser? http://pairedomicsdata.bioinformatics.nl/api/projects

Assuming that works, can you also try retrieving the same URL from within the NPLinker Docker container? You can do this by running it in a different way so it starts a shell instead of running the webapp: ```docker run --rm -it andrewramsay/nplinker /bin/bash```. Once you run that you should see a prompt something like this ```root@someID:/app# ```. Paste in ```wget http://pairedomicsdata.bioinformatics.nl/api/projects``` and run that command. If it works, you should see output like this:

```--2021-07-07 12:14:45--  http://pairedomicsdata.bioinformatics.nl/api/projects
Resolving pairedomicsdata.bioinformatics.nl (pairedomicsdata.bioinformatics.nl)... 137.224.16.5
Connecting to pairedomicsdata.bioinformatics.nl (pairedomicsdata.bioinformatics.nl)|137.224.16.5|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://pairedomicsdata.bioinformatics.nl/api/projects [following]
--2021-07-07 12:14:45--  https://pairedomicsdata.bioinformatics.nl/api/projects
Connecting to pairedomicsdata.bioinformatics.nl (pairedomicsdata.bioinformatics.nl)|137.224.16.5|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 22575 (22K) [application/json]
Saving to: ‘projects’

projects                      100%[=================================================>]  22.05K  --.-KB/s    in 0.03s
```

If loading the URL in your regular browser works but it doesn't work in Docker then that might help narrow down the issue. It could also have just been some transient issue with resolving that particular URL, but if it's failing consistently then something else is wrong.

**Comment by jcpasion** [comment]
I can access it in a regular browser, but not using the Docker shell. Perhaps it's the way Docker is configured on the server, or a permissions issue. I will also try NPLinker on my home computer right now to confirm it's the Docker that's specifically installed on the server I'm using!

**Comment by jcpasion** [comment]
Yes, it works on my home computer, current downloading the files. I will speak to my server admin about our docker install and get back to you when I can.

**Comment by jcpasion** [comment]
Ah my issue was proxy server based, I cleared up those issues and the download works fine now. Thanks for helping isolate the problem!
