### ISSUE TITLE
KeyError in strains.py

### ISSUE THREAD

**Issue by louwenjjr** [sdrogers/nplinker#46]
Hi Andrew,

I am running Crusemann data with a new GNPS run and after adjusting the stain_mappings.csv to include some more links I run into a keyerror. Thanks in advance!

I am running this command:
`
docker run --name webapp --user $(id -u):$(id -g) -p 5006:5006 -v /mnt/scratch/louwe015/NPLinker/own/nplinker_shared:/data:rw andrewramsay/nplinker
`

And running into this error:
`
14:36:58 [INFO] genomics.py:344, # after filtering, total bgcs = 5905, GCFs = 1263, strains=282, unknown_strains=0
14:36:59 [WARNING] loader.py:520, Writing unknown strains from GENOMICS data to /data/crus_new_gnps_AS3/unknown_strains_gen.csv
2021-07-22 14:36:59,040 Error in server loaded hook KeyError('AZWI01000000',)
Traceback (most recent call last):
  File "/app/conda/envs/bigscape/lib/python3.6/site-packages/bokeh/server/contexts.py", line 173, in run_load_hook
    self._application.on_server_loaded(self.server_context)
  File "/app/conda/envs/bigscape/lib/python3.6/site-packages/bokeh/application/application.py", line 186, in on_server_loaded
    h.on_server_loaded(server_context)
  File "/app/conda/envs/bigscape/lib/python3.6/site-packages/bokeh/application/handlers/directory.py", line 232, in on_server_loaded
    return self._lifecycle_handler.on_server_loaded(server_context)
  File "/app/conda/envs/bigscape/lib/python3.6/site-packages/bokeh/application/handlers/lifecycle.py", line 75, in on_server_loaded
    return self._on_server_loaded(server_context)
  File "/app/webapp/npapp/server_lifecycle.py", line 58, in on_server_loaded
    nh.load()
  File "/app/webapp/npapp/server_lifecycle.py", line 22, in load
    self.load_nplinker()
  File "/app/webapp/npapp/server_lifecycle.py", line 41, in load_nplinker
    if not self.nplinker.load_data():
  File "/app/webapp/npapp/../../prototype/nplinker/nplinker.py", line 243, in load_data
    if not self._loader.load(met_only=met_only):
  File "/app/webapp/npapp/../../prototype/nplinker/loader.py", line 235, in load
    self._filter_only_common_strains()
  File "/app/webapp/npapp/../../prototype/nplinker/loader.py", line 313, in _filter_only_common_strains
    self.strains.filter(common_strains)
  File "/app/webapp/npapp/../../prototype/nplinker/strains.py", line 68, in filter
    self.remove(strain)
  File "/app/webapp/npapp/../../prototype/nplinker/strains.py", line 60, in remove
    del self._lookup[alias]
KeyError: 'AZWI01000000'
`

**Comment by andrewramsay** [comment]
I could modify the code to handle this situation without throwing a KeyError, but I'd like to find out why it's happening first because it might indicate another problem somewhere. 

At this stage of the loading process it's gathered a separate list of strains from the metabolomics and genomics data, and is merging them together to only leave the list of strains common to both. Part of that process involves deleting entries from the central set of strain mappings, and the error is happening because it tries to delete an entry that has apparently already been deleted. 

If this started happening after you edited strain_mappings.csv, is it possible there are currently 2 strains listed in it which both have "AZWI01000000" as an alternative label? I'm wondering if the reason for the KeyError is that the label was removed when the first strain was removed, then it tries to remove it again when handling the second strain but finds that entry is already gone.

**Comment by louwenjjr** [comment]
Thanks for your rapid reply and explanation!
Indeed, finding out what is happening makes sense. I only see this key once in my strain mappings file in this line:
Salinispora arenicola CNB458,NZ_KI911444,B458-3-Bu.mzXML,B458-3-Me.mzXML,B458-3-EA.mzXML,AZWI01000000

I uploaded the file so you can see it here: https://bioinformatics.nl/~louwe015/strain_mappings.csv

It should correspond to these antismash files in my antismash folder:
AZWI01000000_KI911444.1.cluster001.gbk
AZWI01000000_KI911444.1.cluster002.gbk
AZWI01000000_KI911444.1.cluster003.gbk
AZWI01000000_KI911444.1.cluster004.gbk

**Comment by louwenjjr** [comment]
Maybe it is because (NZ_)KI911444 is also already an identifier for these files?

**Comment by andrewramsay** [comment]
OK, it doesn't look like it's as simple as having a duplicate label then. If it only appears on one line in your file then that should be fine, even with the alternative NZ_KI911444 label. 

Do you happen to have a copy of your previous version of strain_mappings.csv? If it worked before editing and then this happened afterwards it would be interesting to see what changed, and it might help me pinpoint where things are going wrong.

**Comment by louwenjjr** [comment]
Yes definitely: https://bioinformatics.nl/~louwe015/strain_mappings_original.csv

I was missing quite some labels for the Crusemann dataset (the 145 Salinispora and Streptomyces strains) that I got from the PoDP entry of this dataset (only identifiers from MSV000078836), so I added identifiers from Duncan (MSV000079284) to the strain mappings file and added more identifiers for all the antismash files (apparently some double ones as well).

If you have correct strain_mappings for the complete Crusemann dataset then that would also help a ton! But still good to know where this bug comes from I think.

**Comment by andrewramsay** [comment]
I'm still not sure what's causing this... it would be ideal if I could reproduce it locally, so I've pushed a small update to the Docker image. If you pull & run the new version you will still see the same KeyError, but before it gets to that point you should find it now saves a couple of files to the dataset folder called "original_strains.csv" and "common_strains.csv". The first one will contain the set of all strains it has loaded before attempting to do the filtering step, and the second one will contain the set of strains that should remain after the filtering process. 

If you can attach/upload both of those files I think that will allow me to run the filtering code with the same inputs and that will hopefully let me track what's going on in more detail.

**Comment by louwenjjr** [comment]
Cool. I'm running that now.

**Comment by louwenjjr** [comment]
I uploaded both here: https://bioinformatics.nl/~louwe015/

**Comment by andrewramsay** [comment]
Thanks, that was very helpful! Looks like the problem was actually being caused by the limited set of strain ID mappings included as part of nplinker, nothing to do with your file. 

You can see that [here](https://github.com/sdrogers/nplinker/blob/3355ea639b891802d3623058da23b73c4454aeb3/prototype/nplinker/data/strain_id_mapping.csv#L113) there is an entry for `CNB458` with the same `AZWI01000000` label. So during the filtering step it encountered this entry first and removed `AZWI01000000`. Then when it tried to remove the same label for the `Salinispora arenicola CNB458` line in your strain_mappings.csv, it'd unexpectedly already been deleted and that caused the KeyError. 

From what I remember of our development process, this other strain_id_mapping.csv file was something that was used before we added the ability to load sets of user-supplied strain IDs. I'd completely forgotten it even existed and it doesn't seem to have been updated in well over a year. 

For now I've just deleted the contents of that file, so it won't interfere by adding unexpected extra mappings. Instead everything should now be sourced from your strain_mappings.csv file. The Docker image is updated ready for you to try it out.
