### ISSUE TITLE
Turning MIBiG on in BiG-SCAPE run of NPLinker

### ISSUE THREAD

**Issue by louwenjjr** [sdrogers/nplinker#55]
I noticed that MIBiG is turned off in the NPLinker BiG-SCAPE run, was this done for a particular reason? Because I think it would make a lot more sense to include it by default.

I think it would just be setting mibig_14=True here:
https://github.com/sdrogers/nplinker/blob/e7b79c19771dee4f4a4353309ccab1dcb7b4a55d/prototype/nplinker/pairedomics/runbigscape.py#L26

This will run into this if statement:
https://github.com/sdrogers/nplinker/blob/e7b79c19771dee4f4a4353309ccab1dcb7b4a55d/prototype/nplinker/pairedomics/runbigscape.py#L63-L64

Meaning the --mibig flag will turned on which will use the newest version of MIBiG (2.1). I don't precisely know how the downloading of the compressed MIBiG file happens, maybe this needs to be adjusted as well to include the newest version.

Cheers,
Joris

**Comment by andrewramsay** [comment]
> was this done for a particular reason?

If you're reading through the NPLinker code and find anything that makes you ask this question, the answer will probably be "because I didn't know any better" :) 

I just don't have the background to know what makes sense in a lot of these instances. If I remember correctly I had a script from somewhere that was used to run BiG-SCAPE and simply copied the parameters it used. This was a while ago as you can see from the way "mibig_14" is linked to the "--mibig" parameter when that now actually means "use MiBIG 2.1". 

You should already be able to add this parameter using the "extra_bigscape_parameters" option in the NPLinker config file, but if it would make more sense to have it enabled as a default I'll do that and update the documentation to match.

**Comment by louwenjjr** [comment]
I think it would make more sense to add it by default! Or at least to add a line somewhere explicitly stating that you need to turn on MIBiG when running bigscape, as I think almost everyone wants to use MIBiG as well when using bigscape.
Thanks :)

**Comment by andrewramsay** [comment]
OK, no problem. This should be fixed by commit 457646577ea722a99a41c1458ecafc13e5b7ad2b, and is included in the v1.1.1 Docker image I'll upload shortly. I've also [updated the default config file](https://github.com/sdrogers/nplinker/blob/2fe8c210e202ede4b4c7863be47fd47432b7139c/prototype/nplinker/data/nplinker.toml#L171) to indicate --mibig is the default.

**Comment by sdrogers** [comment]
Sorry - bit late to this. Don’t have a particularly strong preference, but the reason I think why it was off by default is that including 2000 extra data observations into a cluster analysis with (most likely) fewer than 2000 original observations massively biases the results. When looking at using MIBIG we generally felt that the known cluster blast way of incorporating made much more sense.

As long as it’s easy to turn on and off and the docs are clear, it doesn’t matter, but just for context….

**Comment by andrewramsay** [comment]
I'll add a bit more emphasis around that in the documentation then, sounds like something people will want to be aware of when they try NPLinker for the first time.

**Comment by louwenjjr** [comment]
But the MIBiGs are not taken into account in any of the analyses right? They are just added in the GCF as additional info? Or am I mistaken here?

**Comment by justinjjvanderhooft** [comment]
@sdrogers thanks for your thoughts on this - it makes sense to not include them when running a small amount of BGCs, but rather compare afterwards which experimental BGCs match to the MIBiG ones. @louwenjjr if added, they are also part of the clustering analyses! Thus, when you do not have quite some experimental BGCs, they will hugely influence the clustering.

**Comment by louwenjjr** [comment]
I'm not sure I follow completely, please correct me if I miss something of course. But I still don't see why adding the MIBiGs would hugely affect a BiG-SCAPE run with few experimental BGCs, as BiG-SCAPE just constructs a distance matrix right? And then it uses some graph clustering akin to dbscan to group connections into clusters in the best way possible if they are below a cutoff. In theory I think it could perhaps be possible that because a MIBiG BGC is added, two experimental BGCs are put together in a cluster because of their connection to a MIBiG, but this seems like valid information to me. Afterwords MIBiGs are removed from the output that are not included in any GCFs, and then NPLinker only takes MIBiG information into account in the annotations right? So how could adding MIBiG massively influence the results?

**Comment by sdrogers** [comment]
Ultimately, the BGCs that are included in the clustering will determine the clustering. Consider two non-MiBIG BGCs…whether or not they are in the same cluster will potentially change depending on whether or not you include 2000 from MiBIG. In addition, each MiBIG can only appear in a single cluster, so you will almost certainly end up with situations where a measured BGC has high similarity to an MiBIG, but it doesn’t get clustered together because the MiBIG has higher affinity to another cluster. I.e. there is a really unpredictable effective limit to the number of things that will end up being annotated with an MiBIG, and it seems really odd to me that whether or not BGC A ends up being similar to MiBIG X changes depending on the presence of BGC B. It’s all just too unstable for my taste.

If you want to compare measured BGCs with MiBIGs, known cluster blast seems a way better solution. However, it’s ultimately up to each user to so as long as it’s clearly documented….

**Comment by sdrogers** [comment]
@justinjjvanderhooft I would have thought that MiBIG dominates a lot of analyses because many datasets don’t have close to 2000 measured BGCs? Although as time goes on, datasets will probably get bigger quicker than MiBIG will.

**Comment by justinjjvanderhooft** [comment]
@sdrogers it will depend on how many MIBiG BGCs actually match to experimental ones. As the MIBiG database is quite biased in terms of organisms and type of clusters (and will remain to be in the coming time), the impact on the clustering will depend on multiple factors including size of the dataset but also the type of samples.

**Comment by louwenjjr** [comment]
I think good documentation is then indeed nice.

> I.e. there is a really unpredictable effective limit to the number of things that will end up being annotated with an MiBIG, and it seems really odd to me that whether or not BGC A ends up being similar to MiBIG X changes depending on the presence of BGC B

I do think that what you describe still does not matter for the clustering of the experimental BGCs right? It might indeed be that a MIBiG will end up in one of the two GCFs in the scenario you describe, but this does not have any effect on the clustering of the experimental BGCs, just the annotation of them. So indeed, ideally you might want to have this MIBiG included in both GCFs, but including the MIBiGs will give additional annotation information albeit not perfect.

And then also based on Justin's comment, and also based on my experience with BiG-SCAPE, not many MIBiGs end up in the GCFs anyway (especially with 0.3 cutoff) since the experimental BGCs will just differ quite a bit from what is present in MIBiG.

**Comment by justinjjvanderhooft** [comment]
Well, if MIBiG BGCs are added as BGCs to cluster, the situation Simon describes may happen, but I would also say that it is not that likely to occur....

**Comment by sdrogers** [comment]
@louwenjjr if MIBiG is included then the concept of “clustering of the experimental BGCs” isn’t a thing. It’s a clustering of everything. With instance based cluster methods (as opposed to, eg statistical mixtures), the addition / removal of a single BGC can change the resulting clustering profoundly.

I agree with @justinjjvanderhooft in that MIBiG is (naturally) biased and so many of its entries may well have no affinity with the experimental BGCs in any particular experiment. But my main point stands: including MIBiG will change the relationships that bigscape extracts between experimental BGCs wrt what they would be if it wasn’t included, and it does so in a way that is unpredictable. Affinity clustering on its own is pretty unpredictable, but that’s a whole other story….:-)

Using the known cluster blast feature doesn’t have any of these problems. And I don’t see any output that adding MIBiG to the clustering can provide that known cluster blast cannot?

**Comment by justinjjvanderhooft** [comment]
@sdrogers I think we all agree and I think it is a matter of taste what the best default option is. In the end, all clustering is subjective....;-) - let's indicate this well in the documentation and in the future also further support the use of knownclusterblast (and "substructureblast") annotations....
